import gopigo  # this has all the functions related to GoPiGo; not sensors
import time   # Python library that allows us to deal with time

print ("Going Forward")
gopigo.forward()
time.sleep(1)
print ("Going Backward")
gopigo.backward()
time.sleep(1)
print ("Turning to the left")
gopigo.left()
time.sleep(0.5)
print ("Spinning left")
gopigo.left_rot()
time.sleep(0.5)
print ("Turning to the right")
gopigo.right()
time.sleep(0.5)
print ("Spinning right")
gopigo.right_rot()
time.sleep(0.5)
print ("Stopping")
gopigo.stop()
print ("Faster 1 of 3")
gopigo.increase_speed()
gopigo.forward()
time.sleep(1)
print ("Faster 2 of 3")
gopigo.increase_speed()
gopigo.forward()
time.sleep(1)
print ("Faster 3 of 3")
gopigo.increase_speed()
gopigo.forward()
time.sleep(1)
print ("slower 1 of 3")
gopigo.decrease_speed()
gopigo.forward()
time.sleep(1)
print ("slower 2 of 3")
gopigo.decrease_speed()
gopigo.forward()
time.sleep(1)
print ("slower 3 of 3")
gopigo.decrease_speed()
gopigo.forward()
time.sleep(1)
print ("Stopping")
gopigo.stop()

